Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/AbcSize:
  Max: 42

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 60

Metrics/PerceivedComplexity:
  Max: 20

Style/MissingRespondToMissing:
  Exclude:
    - 'lib/xmlhasher.rb'

Naming/VariableNumber:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: <%= ENV['CI'] != 'true' %>
